export enum EstadoLlamadoEnum {
    creado = "Creado",
    enRelevamiento = "Agregando Informacion",
    listoParaEstudioMerito = "Listo para estudio de meritos",
    enEstudioMerito = "En estudio de merito",
    listoParaEntrevistas = "Listo para entrevistas",
    enEntrevias = "En entrevistas",
    listoParaPsicotecnico = "Listo para psicotecnico",
    enPsicotecnico = "En Psicotecnico",
    listoParaFirmarGrilla = "Listo para firmarGrilla",
    enProcesoDeFrimaGrilla = "En proceso de firma Grilla",
    listoParaFirmarActaFinal = "Listo para firmar Acta Final",
    enProcesoDeFrimaActaFinal = "En proceso de firma Acta Final",
    finalizado = "Finalizado",
    eliminado = "Eliminado",
}