import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import styled from "styled-components";
import tw from "twin.macro";
import { Topbar } from "@/components/CheckTokenWrapper/CheckTokenWrapper";
import Breadcrumb from "@/components/Topbar/Breadcrumb";
import ProfileBar from "@/components/Topbar/ProfileBar";
import Button from "@/components/Buttons/Button";
import { BiPlus } from "react-icons/bi";
import Table from "@/components/Table/Table";
import { Columns, formatLlamadosToTable } from "@/utils/llamadoUtils";
import { useQuery } from "@apollo/client";
import { listarLlamados } from "@/controllers/llamadoController";
import { LlamadoList } from "types/llamado";
import { useGlobal } from "@/hooks/useGlobal";
import { useEffect } from "react";
import { useRouter } from "next/router";
import appRoutes from "@/routes/appRoutes";

const Container = styled.div`
  ${tw`w-full max-h-full pb-5 h-auto p-5 py-0 flex gap-4 flex-col items-center justify-start`}
`;

const ActionRow = styled.div`
  ${tw`w-full h-auto flex flex-row items-center justify-end gap-4`}
`;


const Llamados: NextPage = () => {
  const { data, loading: loadingLlamados } = useQuery<{ listarLlamados: LlamadoList[] }>(listarLlamados);
  const { handleSetLoading } = useGlobal();
  const { push } = useRouter();
  
  useEffect(() => {
    handleSetLoading(loadingLlamados);
  }, [loadingLlamados])

  const rows = formatLlamadosToTable(data?.listarLlamados || []);

  return (
    <>
      <Head>
        <title>Llamados</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Container>
      <Topbar>
        <Breadcrumb title="Llamados" />
        <ProfileBar />
      </Topbar>
      <ActionRow>
        <Button
          variant="fill"
          icon={<BiPlus size={20} fontWeight={700} color="white" />}
          text="Agregar Llamado"
          action={() => push(appRoutes.agregarLlamado())}
          className="w-auto"
        />
      </ActionRow>
      <Table title="Llamados" cols={Columns} data={rows} />
    </Container>
    </>
  );
};

export default Llamados;
