import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Llamados: NextPage = () => {
  return (
    <>
      <Head>
        <title>Llamados</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
    </>
  );
};

export default Llamados;
