import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import styled from "styled-components";
import tw from "twin.macro";
import { Topbar } from "@/components/CheckTokenWrapper/CheckTokenWrapper";
import Breadcrumb from "@/components/Topbar/Breadcrumb";
import ProfileBar from "@/components/Topbar/ProfileBar";
import Button from "@/components/Buttons/Button";
import { BiPlus, BiTrash } from "react-icons/bi";
import Table from "@/components/Table/Table";
import { useMutation, useQuery } from "@apollo/client";
import { disabledLlamados } from "@/controllers/llamadoController";
import { useGlobal } from "@/hooks/useGlobal";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import appRoutes from "@/routes/appRoutes";
import ModalConfirmation from "@/components/Modal/components/ModalConfirmation";
import toast from "react-hot-toast";
import {
  deshabilitarTemplates,
  listarTemplates,
} from "@/controllers/templateController";
import { TemplateList } from "types/template";
import { Columns, formatTemplatesToShow } from "@/utils/template";
import Modal from "@/components/Modal/Modal";
import clsx from "clsx";
import EtapasList from "@/components/EtapasList/EtapasList";
import { formatEtapas } from "@/utils/llamadoUtils";

const Container = styled.div`
  ${tw`w-full max-h-full pb-5 h-auto p-5 py-0 flex gap-4 flex-col items-center justify-start`}
`;

const ActionRow = styled.div`
  ${tw`w-full h-auto flex flex-row items-center justify-end gap-4`}
`;

const Templates: NextPage = () => {
  const { data, loading: loadingTemplates } = useQuery<{
    listarTemplates: TemplateList[];
  }>(listarTemplates, {
    fetchPolicy: "no-cache"
  });
  const { handleSetLoading } = useGlobal();
  const { push } = useRouter();
  const [deleteOpen, setDeleteOption] = useState(false);
  const [selectedTemplate, setSelectedTemplate] = useState<any>(null);
  const [openDeleteConfirmModal, setOpenDeleteConfirmModal] = useState(false);
  const [selecteditemsToDelete, setSelectedItemsToDelete] = useState<
    TemplateList[]
  >([]);
  const [handleDisabledTemplates, { loading: loadingDelete }] = useMutation(
    deshabilitarTemplates
  );

  useEffect(() => {
    handleSetLoading(loadingTemplates || loadingDelete);
  }, [loadingTemplates, loadingDelete]);

  const templateInfo = (data?.listarTemplates || [])?.find((item) => item?.id === selectedTemplate?.id)

  const formattedEtapas = formatEtapas(templateInfo?.etapas || []);


  useEffect(() => {
    setSelectedItemsToDelete([]);
  }, [deleteOpen]);

  const rows = formatTemplatesToShow(data?.listarTemplates || []);

  const rowsWithActions = rows?.map((item) => {
    return {
      ...item,
      action: () => setSelectedTemplate(item),
    };
  });

  const handleDelete = async () => {
    const response = await handleDisabledTemplates({
      variables: {
        templates: selecteditemsToDelete?.map((template) =>
          Number(template?.id)
        ),
      },
    });
    if (response?.data?.deshabilitarTemplates?.ok) {
      toast.success("Se deshabilitaron los llamados correctamente");
      setDeleteOption(false);
      setOpenDeleteConfirmModal(false);
    } else {
      toast.error(response?.data?.deshabilitarTemplates?.message);
    }
  };

  const handleRenderContent = () => {
    return <div className="w-full h-auto flex flex-col items-start justify-start gap-4">
      <div className="flex flex-col items-start w-full justify-start gap-2">
        <span className="font-medium">Nombre: <span className="text-left flex-grow w-full font-normal">{templateInfo?.nombre}</span></span>
        <span className="font-medium">Cargo: <span className="text-left flex-grow w-full font-normal">{templateInfo?.cargo?.nombre}</span></span>
        <span className="font-medium flex flex-row gap-2">Color: <div style={{backgroundColor: templateInfo?.color}} className={clsx(`w-6 min-w-[24px] h-6 rounded-lg shadow-sm`)}>{}</div></span>
        <EtapasList 
          etapas={formattedEtapas}
          isView
          setEtapas={() => null}
        />

      </div>
    </div>
  }

  return (
    <>
      <Head>
        <title>Modelos</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Container>
        <Topbar>
          <Breadcrumb title="Modelos" />
          <ProfileBar />
        </Topbar>
        <ActionRow>
          {deleteOpen && selecteditemsToDelete?.length > 0 && (
            <Button
              variant="red"
              text={"Borrar seleccionados"}
              action={() => setOpenDeleteConfirmModal(!openDeleteConfirmModal)}
              className="w-auto"
            />
          )}
          <Button
            variant="outline"
            icon={<BiTrash size={20} fontWeight={700} color="#4318FF" />}
            text={
              !deleteOpen ? "Habilitar selección" : "Deshabilitar selección"
            }
            action={() => setDeleteOption(!deleteOpen)}
            className="w-auto"
          />
          <Button
            variant="fill"
            icon={<BiPlus size={20} fontWeight={700} color="white" />}
            text="Agregar Modelos"
            action={() => push(appRoutes.agregarTemplate())}
            className="w-auto"
          />
        </ActionRow>
        <Table
          multiDisabled={deleteOpen}
          title="Modelos"
          cols={Columns}
          data={rowsWithActions}
          selectedItems={selecteditemsToDelete}
          setSelectedItems={setSelectedItemsToDelete}
        />
        {openDeleteConfirmModal && (
          <ModalConfirmation
            title="Estas seguro que deseas deshabilitar los modelos seleccionados"
            setOpen={setOpenDeleteConfirmModal}
            description="Los Modelos seleccionados se deshabilitaran"
            onSubmit={() => handleDelete()}
            onCancel={() => setOpenDeleteConfirmModal(false)}
            textok="Si, deshabilitar"
            variant="red"
            textcancel="Cancelar"
          />
        )}
        {
          selectedTemplate && <Modal
          textok={"Aceptar"}
          description="Informacion del template"
          onSubmit={() => setSelectedTemplate(null)}
          setOpen={() => setSelectedTemplate(null)}
          content={handleRenderContent()}
          title={`Template ${templateInfo?.nombre}`}
          className=""
        />
        }
      </Container>
    </>
  );
};

export default Templates;
