import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import styled from "styled-components";
import tw from "twin.macro";
import { Topbar } from "@/components/CheckTokenWrapper/CheckTokenWrapper";
import Breadcrumb from "@/components/Topbar/Breadcrumb";
import ProfileBar from "@/components/Topbar/ProfileBar";
import Button from "@/components/Buttons/Button";
import { BiPlus, BiTrash } from "react-icons/bi";
import Table from "@/components/Table/Table";
import { useMutation, useQuery } from "@apollo/client";
import {
  disabledLlamados,
} from "@/controllers/llamadoController";
import { useGlobal } from "@/hooks/useGlobal";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import appRoutes from "@/routes/appRoutes";
import ModalConfirmation from "@/components/Modal/components/ModalConfirmation";
import { toast } from "react-toastify";
import { deshabilitarTemplates, listarTemplates } from "@/controllers/templateController";
import { TemplateList } from "types/template";
import { Columns, formatTemplatesToShow } from "@/utils/template";

const Container = styled.div`
  ${tw`w-full max-h-full pb-5 h-auto p-5 py-0 flex gap-4 flex-col items-center justify-start`}
`;

const ActionRow = styled.div`
  ${tw`w-full h-auto flex flex-row items-center justify-end gap-4`}
`;

const Templates: NextPage = () => {
  const { data, loading: loadingTemplates } = useQuery<{
    listarTemplates: TemplateList[];
  }>(listarTemplates);
  const { handleSetLoading } = useGlobal();
  const { push } = useRouter();
  const [deleteOpen, setDeleteOption] = useState(false);
  const [openDeleteConfirmModal, setOpenDeleteConfirmModal] = useState(false);
  const [selecteditemsToDelete, setSelectedItemsToDelete] = useState<
    TemplateList[]
  >([]);
  const [handleDisabledTemplates, { loading: loadingDelete }] =
    useMutation(deshabilitarTemplates);

  useEffect(() => {
    handleSetLoading(loadingTemplates || loadingDelete);
  }, [loadingTemplates, loadingDelete]);

  useEffect(() => {
    setSelectedItemsToDelete([]);
  }, [deleteOpen]);

  const rows = formatTemplatesToShow(data?.listarTemplates || []);

  const handleDelete = async () => {
    const response = await handleDisabledTemplates({
      variables: {
        templates: selecteditemsToDelete?.map((template) => Number(template?.id)),
      },
    });
    if (response?.data?.deshabilitarTemplates?.ok) {
      toast.success("Se deshabilitaron los llamados correctamente");
      setDeleteOption(false);
      setOpenDeleteConfirmModal(false);
    } else {
      toast.error(response?.data?.deshabilitarTemplates?.message);
    }
  };

  return (
    <>
      <Head>
        <title>Templates</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Container>
        <Topbar>
          <Breadcrumb title="Templates" />
          <ProfileBar />
        </Topbar>
        <ActionRow>
          {deleteOpen && selecteditemsToDelete?.length > 0 && (
            <Button
              variant="red"
              text={"Borrar seleccionados"}
              action={() => setOpenDeleteConfirmModal(!openDeleteConfirmModal)}
              className="w-auto"
            />
          )}
          <Button
            variant="outline"
            icon={<BiTrash size={20} fontWeight={700} color="#4318FF" />}
            text={
              !deleteOpen ? "Habilitar seleccion" : "Deshabilitar seleccion"
            }
            action={() => setDeleteOption(!deleteOpen)}
            className="w-auto"
          />
          <Button
            variant="fill"
            icon={<BiPlus size={20} fontWeight={700} color="white" />}
            text="Agregar Template"
            action={() => push(appRoutes.agregarTemplate())}
            className="w-auto"
          />
        </ActionRow>
        <Table
          multiDisabled={deleteOpen}
          title="Templates"
          cols={Columns}
          data={rows}
          selectedItems={selecteditemsToDelete}
          setSelectedItems={setSelectedItemsToDelete}
        />
        {openDeleteConfirmModal && (
          <ModalConfirmation
            title="Estas seguro que deseas deshabilitar los templates seleccionados"
            setOpen={setOpenDeleteConfirmModal}
            description="Los templates seleccionados se deshabilitaran"
            onSubmit={() => handleDelete()}
            onCancel={() => setOpenDeleteConfirmModal(false)}
            textok="Si, deshabilitar"
            variant="red"
            textcancel="Cancelar"
          />
        )}
      </Container>
    </>
  );
};

export default Templates;
